Refactor all cron-based GitHub Actions workflows (#1233)

diff --git a/.github/workflows/daily-backup.yml b/.github/workflows/daily-backup.yml
--- a/.github/workflows/daily-backup.yml
+++ b/.github/workflows/daily-backup.yml
@@ -12,6 +12,8 @@ on:
 jobs:
   backup:
     runs-on: ubuntu-latest
+    strategy:
+      matrix: ${{ fromJSON(vars.DEPLOYMENT_MATRIX) }}
 
     steps:
     - name: Install SSH client
@@ -21,35 +23,36 @@ jobs:
       uses: shimataro/ssh-key-action@v2
       with:
         key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
-        known_hosts: ${{ vars.SERVER_HOSTNAME }}
+        known_hosts: ${{ matrix.hostname }}
         config: |
-          Host ${{ vars.SERVER_HOSTNAME }}
-            User ${{ secrets.SERVER_SSH_USERNAME }}
+          Host ${{ matrix.hostname }}
+            User ${{ vars.SSH_USERNAME }}
             StrictHostKeyChecking no
 
     - name: Execute Backup on Server
       run: |
-        ssh ${{ secrets.SERVER_SSH_USERNAME }}@${{ vars.SERVER_HOSTNAME }} << 'EOF'
+        ssh ${{ vars.SSH_USERNAME }}@${{ matrix.hostname }} << 'EOF'
           set -e
-          cd ~/app
 
+          cd ~
           mkdir -p backups
           rm -rf backups/*
 
-          for env_file in .env*; do
-            [ -e "$env_file" ] || continue
+          for env_file in ${{ matrix.env_files }}; do
+            ENV="app/$env_file"
+            [ -e "$ENV" ] || continue
 
             # Extract DATABASE_URI and DATABASE_BACKUP_KEY
-            DATABASE_URI=$(grep '^DATABASE_URI=' "$env_file" | sed -e 's/^DATABASE_URI=//' | sed -e "s/^'//;s/'$//" | sed -e 's/^"//;s/"$//')
-            DATABASE_BACKUP_KEY=$(grep '^DATABASE_BACKUP_KEY=' "$env_file" | sed -e 's/^DATABASE_BACKUP_KEY=//' | sed -e "s/^'//;s/'$//" | sed -e 's/^"//;s/"$//')
+            DATABASE_URI=$(sudo grep '^DATABASE_URI=' "$ENV" | sed -e 's/^DATABASE_URI=//' | sed -e "s/^'//;s/'$//" | sed -e 's/^"//;s/"$//')
+            DATABASE_BACKUP_KEY=$(sudo grep '^DATABASE_BACKUP_KEY=' "$ENV" | sed -e 's/^DATABASE_BACKUP_KEY=//' | sed -e "s/^'//;s/'$//" | sed -e 's/^"//;s/"$//')
 
             if [ -n "$DATABASE_URI" ] && [ -n "$DATABASE_BACKUP_KEY" ]; then
-              echo "Backing up database for $env_file"
+              echo "Backing up database for $ENV"
               pg_dump "$DATABASE_URI" -F p -b -v -f backup.sql && gzip -f backup.sql
               openssl enc -aes-256-cbc -salt -pbkdf2 -pass "pass:$DATABASE_BACKUP_KEY" -in backup.sql.gz -out backups/backup_${env_file}.sql.gz.enc
               rm -f backup.sql backup.sql.gz
             else
-              echo "Skipping $env_file: DATABASE_URI or DATABASE_BACKUP_KEY not found."
+              echo "Skipping $ENV: DATABASE_URI or DATABASE_BACKUP_KEY not found."
             fi
           done
 
@@ -59,15 +62,15 @@ jobs:
 
     - name: Download Backup Archive
       run: |
-        scp ${{ secrets.SERVER_SSH_USERNAME }}@${{ vars.SERVER_HOSTNAME }}:~/app/all_backups.tar ./all_backups.tar
+        scp ${{ vars.SSH_USERNAME }}@${{ matrix.hostname }}:~/all_backups.tar ./all_backups.tar
 
     - name: Clean up remote backup archive
       run: |
-        ssh ${{ secrets.SERVER_SSH_USERNAME }}@${{ vars.SERVER_HOSTNAME }} "rm -f ~/app/all_backups.tar"
+        ssh ${{ vars.SSH_USERNAME }}@${{ matrix.hostname }} "rm -f ~/all_backups.tar"
 
     - name: Upload Backup to Artifacts
       uses: actions/upload-artifact@v4
       with:
-        name: database-backups
+        name: database-backups-${{ matrix.host_id }}
         path: all_backups.tar
         retention-days: 30
